PREFIX = ../../
BUTFILES =
NTN = -f $(PREFIX)/examples/omstd/quant1.ntn -f $(PREFIX)/examples/omstd/logic1.ntn -f $(PREFIX)/examples/logics/simpletypes.ntn

include $(PREFIX)/lib/Makefile.vars
all: pres
include $(PREFIX)/lib/Makefile.in

