PREFIX          = ../..
COLLFILES       = 
BUTFILES 	= accounting.omdoc
include $(PREFIX)/lib/Makefile.vars

all:		html
2:		42 i2 mml2
collection:	collection.html collection.xml collection.ps
include $(PREFIX)/lib/Makefile.in
