PREFIX  = ../..
PART	= processing
TARGET	= main #errata
RawTEXSRC	= $(shell ls *.tex) 
include $(PREFIX)/doc/Makefile.vars
include ../lib/Makefile.vars

all:	main.pdf #errata.pdf

include $(PREFIX)/doc/Makefile.in
include ../lib/Makefile.in
include $(PREFIX)/lib/Makefile.clean.in

