PREFIX          = ../..
COLLFILES       = collection.omdoc
BUTFILES	= prefixed.omdoc

include $(PREFIX)/lib/Makefile.vars
include $(PREFIX)/lib/Makefile.test.vars

all:		pres
include $(PREFIX)/lib/Makefile.in
include $(PREFIX)/lib/Makefile.test.in

#echo:	
#	echo $(NTNFILES)


