# the path where you have Jena (the Java RDF API) installed
JENA_LIB		= $(HOME)/svn/kwarc.info/swim/trunk/WEB-INF/lib

# the Java classpath where info.kwarc.semweb.OWLMerge can be found (sources available from https://svn.salzburgresearch.at/svn/kiwi/IkeWiki/branches/SWiM/trunk/WEB-INF/src)
OWLMERGE_CLASSPATH	= $(HOME)/svn/kwarc.info/swim/trunk/build/dest/WEB-INF/classes

# command name to use for Subversion operations
SUBVERSION = locutor
