PREFIX          = ..
INSTALLDIRS	= primer projects spec blue #processing book
MAKEDIRS 	= $(INSTALLDIRS)
TESTDIRS	= # $(MAKEDIRS) # nothing to test in doc
CLEANDIRS	= $(MAKEDIRS) 
include $(PREFIX)/lib/Makefile.subdirs
