PREFIX          = ../..
TESTDIRS = 	adt algebra cc cd complex-theories courseware dc document document-model ext\
		math-markup mobj mtext pres proofs quiz richtext spec-intro\
		statements xmlrpc development-graph natlist combined
CLEANDIRS =	$(TESTDIRS)

include $(PREFIX)/lib/Makefile.subdirs
